#!/bin/bash

########################  MAIN

_echot "------- install"
packages="ghex wxhexeditor"
# for bless SEE https://miloserdov.org/?p=5666
# sysstat mkisofs bless
_install_pcks ${packages}

if ! which imhex >/dev/null; then
	_echot "------- imhex"
	anstmp=1.37.4-Ubuntu-24.04-x86_64
	_echoa "url to see available releases: https://github.com/WerWolv/ImHex/tags"
	_askno "Give the version to download imhex from github (${anstmp})"
	imhex_version=${_ANSWER:-${anstmp}}
	file=imhex-${imhex_version}.deb
	pth=/tmp/${file}
	if ! [ -f ${pth} ]; then
		url=https://github.com/WerWolv/ImHex/releases/download/v${imhex_version%%-*}/${file}
		_eval wget -qO ${pth} ${url} || _exite "Error while downloading url: ${url}"
	fi

	_echot "------- install"
	_evalr apt install -y -f ${pth} || _exite "Unable to install ${pth}"
fi
