#!/bin/bash

########################  INSTALL

_echot "------- tools"
packages="jq lnav kpartx neovim openssh-server pv squashfs-tools"
packages+=" genisoimage net-tools xsysinfo"
_install_pcks ${packages}

_echot "------- softs"
packages="geany git gitg gitk gtkhash vim"
# bless mkisofs sysstat
_install_pcks ${packages}

_echot "------- extra"
packages=" openjdk-21-jre"
# sysstat
_install_pcks ${packages}

########################  CONF

_echot "------- conf geany"
pth=${HOME}/.config/geany/colorschemes
[ -d "${pth}" ] || mkdir -p ${pth}
cp ${_PATH_BASE}/conf/geany/* ${pth}/
