#!/bin/bash

########################  MAIN

_echot "------- install"
packages="cython3 python3-pip pipx"
_install_pcks ${packages}

packages="virtualenv grip"
for package in ${packages}; do
	_echot "------- pipx"
	_eval pipx install ${package}
done
