#!/bin/bash

########################  MAIN
# xprop WM_CLASS

dir=~/.config/autostart
! [ -d ${dir} ] && mkdir ${dir}

_echot "------- remove tangerine"

files="${dir}/tangerine-autostart.desktop \
/etc/xdg/autostart/tangerine-autostart.desktop \
/etc/xdg/autostart/gnome-do.desktop"
for file in ${file}s; do [ -f ${file} ] && (! grep -q X-GNOME-Autostart-enabled "${file}" && sudo sed -i '2iX-GNOME-Autostart-enabled=false' "${file}" || sudo sed -i 's|^\(X-GNOME-Autostart-enabled=\).*$|\1false|' "${file}"); done

_echot "------- firefox add disabled"

file=${dir}/00-firefox.desktop
echo "[Desktop Entry]
Version=1.0
Name=Firefox Web Browser
Comment=Browse the World Wide Web
GenericName=Web Browser
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=firefox -P xenialg
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
DBusActivatable=true
X-GNOME-Autostart-Delay=0
X-GNOME-Autostart-enabled=false" > ${file}
chmod +x "${file}"

_echot "------- nautilus add disabled"

file=${dir}/20-org.gnome.Nautilus.desktop
echo "[Desktop Entry]
Name=Files
Comment=Access and organize files
Keywords=dir;manager;explore;disk;filesystem;
Exec=nautilus --new-window sftp://root@node1/usr/local/bs
Icon=system-file-manager
Terminal=false
Type=Application
Categories=GNOME;GTK;Utility;Core;FileManager;
StartupNotify=true
DBusActivatable=true
X-GNOME-Autostart-Delay=2
X-GNOME-Autostart-enabled=false" > ${file}
chmod +x "${file}"

_echot "------- terminal add disabled"

file=${dir}/40-gnome-terminal.desktop
echo "[Desktop Entry]
Name=Terminal
Comment=Use the command line
Keywords=shell;prompt;command;commandline;cmd;
#Exec=gnome-terminal --tab --tab -e 'ssh-server node1'
Exec=gnome-terminal --tab --tab-with-profile node1
Icon=utilities-terminal
Type=Application
#Hidden=false
#NoDisplay=false
StartupNotify=true
DBusActivatable=true
X-GNOME-Autostart-Delay=4
X-GNOME-Autostart-enabled=false" > ${file}
chmod +x "${file}"
