#!/bin/bash

# _GIT_BR
_menu "Select 'main' or 'dev' branch to be used by installer (main)" main dev
_GIT_BR=${_ANSWER}
_confset _GIT_BR "${_GIT_BR}"

# _BTRFS
if [ -z ${_BTRFS+x} ]; then
	_askyn "BTRFS are used for system?"
	_BTRFS=${_ANSWER/n/}
	[ ${_ANSWER} = y ] && _BTRFS=btrfs || _BTRFS=nobtrfs
	_confset _BTRFS "${_BTRFS}"
fi
[ "${_BTRFS}" ] && part_fs="btrfs" || part_fs="nobtrfs"

# _HALT
if [ -z ${_HALT+x} ]; then
	_askyn "Enable halt between each parts?"
	_HALT=${_ANSWER/n/}
	_confset _HALT "${_HALT}"
fi
