#!/bin/bash

########################  MAIN

_echot "------- system"
packages="curl wget duf exfatprogs gnupg hfsprogs htop most ncdu pv testdisk tree"
packages+=" git gparted tmux vim"
packages+=" p7zip-full pigz zstd"
# kpartx ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin p7zip-rar 
_install_pcks ${packages}

_echot "------- tools"
packages="dconf-editor dconf-cli font-manager meld plank qt6ct stopwatch"
# qt5ct
packages+=" gnome-activity-journal gnome-system-monitor"
# boot-repair backintime-gnome y-ppa-manager numlockx multisystem baobab gnome-system-tools gnome-tweaks gnome-sushi"
_install_pcks ${packages}

_echot "------- office"
packages="scribus"
_install_pcks ${packages}

_echot "------- graphic "
packages="inkscape"
# inkscape-speleo inkscape-textext inkscape-tutorials inkscape-open-symbols inkscape-survex-export"
packages+=" gimp gimp-data-extras gimp-texturize"
# gimp-lensfun gimp-plugin-registry
_install_pcks ${packages}

_echot "------- media"
packages="mpv totem totem-plugins"
packages+=" simplescreenrecorder"
# cheese obs-studio vlc
_install_pcks ${packages}

_echot "------- media-extras"
packages="gstreamer1.0-plugins-good gstreamer1.0-plugins-bad"
packages+=" libavcodec-extra"
_install_pcks ${packaegs}

_echot "------- audio"
packages="audacity easytag sayonara soundconverter sound-juicer"
# chrome-gnome-shell
_install_pcks ${packages}

_echot "------- video"
packages="aegisub handbrake mkvtoolnix-gui"
_install_pcks ${packages}
