#!/bin/bash

########################  PRE OUTSIDE

_echot "------- ttf"
_echo "Launch this following command in an other terminal:"
_echoA "sudo apt install -y ttf-mscorefonts-installer"
_askno "After it, Validate to continue"

########################  MAIN

_echot "------- system"
packages="curl wget duf exfatprogs gnupg hfsprogs htop most ncdu pv testdisk tree"
packages+=" git gparted tmux vim"
packages+=" p7zip-full pigz zstd"
# kpartx ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin p7zip-rar 
_install_pcks ${packages}

_echot "------- tools"
packages="dconf-editor dconf-cli font-manager meld plank qt6ct stopwatch"
packages+=" gnome-activity-journal gnome-system-monitor"
# qt5ct boot-repair backintime-gnome y-ppa-manager numlockx multisystem baobab gnome-system-tools gnome-tweaks gnome-sushi"
_install_pcks ${packages}

_echot "------- office"
packages="scribus"
_install_pcks ${packages}

_echot "------- graphic "
packages="inkscape"
# inkscape-speleo inkscape-textext inkscape-tutorials inkscape-open-symbols inkscape-survex-export"
packages+=" gimp gimp-data-extras gimp-texturize"
# gimp-lensfun gimp-plugin-registry
_install_pcks ${packages}

_echot "------- media"
packages="guvcview mpv totem totem-plugins vlc vokoscreen-ng"
# obs-studio simplescreenrecorder
_install_pcks ${packages}

_echot "------- media-extras"
packages="gstreamer1.0-plugins-good gstreamer1.0-plugins-bad"
packages+=" libavcodec-extra ubuntu-restricted-extras"
_install_pcks ${packages}

_echot "------- audio"
packages="audacity easytag sayonara soundconverter sound-juicer"
# chrome-gnome-shell
_install_pcks ${packages}

_echot "------- video"
packages="aegisub handbrake mkvtoolnix-gui"
# gnome-subtitles
_install_pcks ${packages}
