#!/bin/bash

########################  PRE OUTSIDE

# _echot "------- ttf"
# _echo "Launch this following command in an other terminal:"
# _echoA "sudo apt install -y ttf-mscorefonts-installer"
# _askno "After it, Validate to continue"

########################  MAIN

_echot "------- system"
packages="curl wget duf exfatprogs gnupg hfsprogs htop most ncdu pv testdisk tree"
packages+=" git gparted tmux vim"
packages+=" p7zip-full p7zip-rar pigz zstd"
# kpartx ntfsprogs grsync gtk2-engines-pixbuf libnss-myhostname atop fslint dstat icedtea-8-plugin
_install_pcks ${packages}

_echot "------- tools"
packages="dconf-editor font-manager gnome-sushi meld qt5ct qt6ct stopwatch"
packages+=" gnome-activity-journal gnome-system-monitor gnome-system-tools gnome-tweaks"
# boot-repair backintime-gnome y-ppa-manager numlockx multisystem baobab
packages+=" nautilus-sendto"
# easytag-nautilus nautilus-script-audio-convert nautilus-columns
# nautilus-image-manipulator filemanager-actions nautilus-emblems
# uget-chrome-wrapper nautilus-dropbox nautilus-filename-repairer nautilus-image-converter nautilus-terminal
# compiz-fusion-plugins-extra compizconfig-settings-manager exfat-utils exfat-fuse freefilesync qshutdown solaar unetbootin
_install_pcks ${packages}

_echot "------- office"
packages="scribus"
_install_pcks ${packages}

_echot "------- graphic "
packages="inkscape"
# inkscape-speleo inkscape-textext inkscape-tutorials inkscape-open-symbols inkscape-survex-export"
packages+=" gimp gimp-data-extras gimp-texturize"
# gimp-lensfun gimp-plugin-registry
_install_pcks ${packages}

_echot "------- media"
packages=" cheese mpv totem totem-plugins"
packages+=" simplescreenrecorder obs-studio"
_install_pcks ${packages}

_echot "------- media-extras"
packages=" gnome-video-effects gstreamer1.0-plugins-bad gstreamer1.0-plugins-good"
packages+=" libavcodec-extra"
_install_pcks ${packages}

_echot "------- audio"
packages=" audacity easytag sayonara soundconverter sound-juicer"
# chrome-gnome-shell
_install_pcks ${packages}

_echot "------- video"
packages=" aegisub gnome-subtitles handbrake mkvtoolnix-gui"
