#!/bin/bash

########################  REQUIRED

_echot "------- required paths"
pth_install_bash_completion=${_PATH_BASE}/xtra/bash-completion
_requirep ${pth_install_bash_completion}

_echot "------- required files"
file_env=${_PATH_BASE}/bs/conf/.sh_env
file_sh_aliases=${_PATH_BASE}/bs/conf/.sh_aliases
file_sh_functions=${_PATH_BASE}/bs/conf/.sh_functions
_require ${file_env} ${file_sh_aliases} ${file_sh_functions}

########################  SYSTEM

_echot "------- global vatiables"
export S_PATH_SCRIPT=/usr/local/bs
export S_GLOBAL_CONF=/usr/local/conf/global.conf
export S_GLOBAL_FUNCTIONS="/usr/local/bs/inc-functions"

_echot "------- root user"
_askno "Give the password for root or leave blank to let unset"
[ "${_ANSWER}" ] && echo -e "${_ANSWER}\n${_ANSWER}" | sudo passwd root

_echot "------- grub"
file=/etc/default/grub
_keepcpts ${file}
sudo sed -i "s|^.\?\(GRUB_TIMEOUT_STYLE\)=.*|\1=menu|" ${file}
sudo sed -i "/^GRUB_TIMEOUT=/ s|=.*|=2|" ${file}
sudo sed -i "/^GRUB_DEFAULT=/ s|=.*|=0|" ${file}
sudo sed -i "/^GRUB_SAVEDEFAULT=/ s|=.*|=false|" ${file} # manjaro
sudo sed -i "/^GRUB_DISABLE_OS_PROBER=T=/ s|=.*|=false|" ${file}
grep -q '^GRUB_DISABLE_OS_PROBER' ${file} || sudo sh -c "echo 'GRUB_DISABLE_OS_PROBER=false' >> ${file}"

file=/etc/grub.d/00_header
_evalr cp -a ${file} ${file}.${_SDATE} && _evalr chmod -x ${file}.${_SDATE}
sudo sed -i "s|30|2|g" ${file}

if [ "${_BTRFS}" ];then
	_echot "------- grub install"
	_evalr grub-install ${_DEVICE_GRUB}
fi

_echot "------- grub update"
_evalr update-grub

_echot "------- reduce swapiness"
_evalr swapoff -av
sudo sh -c 'echo vm.swappiness=40 > /etc/sysctl.d/99-swappiness.conf' # limit swap
_evalr swapon -v

_echot "------- conf mirror sources"
_echoA "After validation, select the country for software sources mirror"
_askno "Validate to continue"
software-properties-gtk

########################  USER

_echot "------- user paths"
pths="${HOME}/.local/bin ${HOME}/.local/share/icons ${HOME}/.local/share/applications"
for pth in ${pths}; do
	[ -d "${pth}" ] || mkdir -p ${pth}
done

_echot "------- global conf"
file=${S_GLOBAL_CONF}
[ -f "${file}" ] || touch ${file}

_echot "------- .sh_env"
file=${HOME}/.sh_env
_keepmvts ${file}
_eval cp -a ${file_env} ${file}
_evalr chmod 644 ${file}

_echot "------- .sh_aliases"
file=~/.sh_aliases
_keepmvts ${file}
_eval cp -a ${file_sh_aliases} ${file}
_evalr chmod 644 ${file}

_echot "------- .sh_functions"
file=~/.sh_functions
_keepmvts ${file}
_eval cp -a ${file_sh_functions} ${file}
_evalr chmod 644 ${file}

file=~/.bashrc
if ! [ -f ${file} ]; then
	_echot "------- init .bashrc"
	[ -f /etc/skel/.bashrc ] || _exite "Unable to find file: '/etc/skel/.bashrc'"
	_evalr cp -a /etc/skel/.bashrc ${HOME}/
	_evalr chown ${USER}:${USER} ${file}
	_evalr chmod 644 ${file}
fi

# force color
sudo sed -i '/^#force_color_prompt=/ s|#||' ~/.bashrc

_echot "------- common .*hrc"
for file in ~/.bashrc ~/.zshrc; do
	_keepcpts ${file}
	grep -sq '####  PERSO' ${file} || echo "
########################  PERSO

# HISTORY
HISTSIZE=50000
HISTFILESIZE=50000

# source global variables
[ -f ~/.sh_env ] && . ~/.sh_env

# aliases
[ -f ~/.sh_aliases ] && . ~/.sh_aliases

# functions
[ -f ~/.sh_functions ] && . ~/.sh_functions
" >> ${file}
	_evalr chmod 644 ${file}
done

_echot "------- .bashrc"
color='\[\033[01;34m\]'
color_root='\[\033[01;31m\]'
file=~/.bashrc
	grep -q '# PS1$' ${file} || echo "
# PS1
if [[ \${EUID} == 0 ]]; then
	PS1='${color_root}\\u@\\h \\[\\033[1;37m\\]\\w${color_root}\\$\\[\\033[00m\\] '
else
	PS1='${color}\\u@\\h\\[\\033[01;37m\\] \\[\\033[1;37m\\]\\w${color}\\$\\[\\033[00m\\] '
fi
" >> ${file}

_echot "------- bash-completion"
_evalr "cp -a ${pth_install_bash_completion}/* /usr/share/bash-completion/completions/"
