#!/bin/bash

########################  DATA

_echot "------- Devices"
sudo lsblk -e 11,7 -o name,size,mountpoint
echo
sudo blkid|grep -v /loop
echo

devices=$( sudo blkid -o device|grep -v '/loop\|/sr' )

if [ -z ${_UEFI+x} ]; then
	menutmp=$( sudo blkid|grep -i 'TYPE="vfat"'|cut -d':' -f1|sort|xargs )
	_menu "Select a device for UEFI or none" none ${menutmp}
	_UEFI=${_ANSWER/none/}
	_confset _UEFI "${_UEFI}"
fi
[ "${_UEFI}" ] && devices=$( sudo blkid -o device|grep -v '/loop\|/sr'|grep -v "${_UEFI}" )

if [ -z ${_DEVICE_SYS+x} ]; then
	_menu "Select a device for SYSTEM" ${devices}
	_DEVICE_SYS=${_ANSWER}
	_confset _DEVICE_SYS "${_DEVICE_SYS}"
fi
[ "${_DEVICE_SYS}" ] && devices=$( echo "${devices}"|grep -v "${_DEVICE_SYS}" )

if [ -z ${_DEVICE_HOME+x} ]; then
	_menu "Select a dedicated device for HOME or none" none ${devices}
	_DEVICE_HOME=${_ANSWER/none/}
	_confset _DEVICE_HOME "${_DEVICE_HOME}"
fi
[ "${_DEVICE_HOME}" ] && devices=$( echo "${devices}"|grep -v "${_DEVICE_HOME}" )

if [ -z ${_DEVICE_EXT+x} ]; then
	_menu "Select a dedicated device for /ext or none" none ${devices}
	_DEVICE_EXT=${_ANSWER/none/}
	_confset _DEVICE_EXT "${_DEVICE_EXT}"
fi

if [ -z ${_MEM+x} ]; then
	anstmp=2G
	_askno "Give the TMPFS memory size for /tmp or 0 (${anstmp})"
	_MEM=${_ANSWER:-${anstmp}}
	_MEM=${_MEM%%0*}
	_confset _MEM "${_MEM}"
fi

if [ -z ${_USERNAME+x} ]; then
	anstmp="nikita"
	_askno "Give the user name (${anstmp})"
	_USERNAME=${_ANSWER:-${anstmp}}
	_confset _USERNAME "${_USERNAME}"
fi

########################  MAIN

_echo "------- --------"
cat "${S_FILE_INSTALL_CONF}"
_echo "------- --------"
_askyn "Confirm installation" && [ "${_ANSWER}" == n ] && _exit 1

###########  MOUNT _DEVICE_SYS pth_sys

_echot "------- device sys"
if ! grep -q "${_DEVICE_SYS}" /proc/mounts; then
	pth=/mnt_sys
	[ -d "${pth}" ] || _evalr mkdir -p "${pth}"
	_evalr mount ${_DEVICE_SYS} ${pth} || _exite "Unable to mount ${_DEVICE_SYS} in ${pth}"
fi
pth_sys=$( grep "${_DEVICE_SYS}" /proc/mounts | cut -d' ' -f2 )
[ -z "${pth_sys}" ] && _exite "${pth_sys} not mounted ?"

###########  MOUNT _DEVICE_HOME pth_home

_echot "------- device home"
if [ "${_DEVICE_HOME}" ]; then
	if ! grep -q "${_DEVICE_HOME}" /proc/mounts; then
		pth=/mnt_home
		[ -d "${pth}" ] || _evalr mkdir -p "${pth}"
		_evalr mount ${_DEVICE_HOME} ${pth} || _exite "Unable to mount ${_DEVICE_HOME} in ${pth}"
	fi
	pth_home=$( grep "${_DEVICE_HOME}" /proc/mounts | cut -d' ' -f2 )
	[ -z "${pth_home}" ] && _exite "${pth_home} not mounted ?"
else
	pth_home=${pth_sys}/home
fi

_echot "------- user"
uid=$( grep ^${_USERNAME} ${pth_sys}/etc/passwd | cut -d: -f3 )
[ -z "${uid}" ] && uid=1000 && _echo "uid set to 1000" 
gid=$( grep ^${_USERNAME} ${pth_sys}/etc/group | cut -d: -f3 )
[ -z "${gid}" ] && gid=1000 && _echo "gid set to 1000" 

_echot "------- create paths"
for pth in ${pth_sys}/save ${pth_sys}/ext ${pth_sys}/vm; do
	[ -d "${pth}" ] || _evalr mkdir -p "${pth}"
	_evalr chown ${uid}:${gid} "${pth}"
done
_evalr chown 0:${gid} "${pth_sys}/vm"
_evalr chmod g+rw "${pth_sys}/vm"

########################  FSTAB

_echot "------- fstab"
file=${pth_sys}/etc/fstab
_keepcpts ${file}

if [ "${_MEM}" ]; then
	_echot "------- fstab tmpfs"
	if grep -q '^tmp.*/tmp' /etc/fstab; then
		sudo sed -i "/tmpfs/ s|mode=1777|mode=1777,size=${_MEM}|" ${file}
	else
		sudo sh -c "echo '
tmpfs                                       /tmp              tmpfs   defaults,noatime,mode=1777,size=${_MEM}     0 0' >> ${file}"
	fi
fi

if [ "${_DEVICE_EXT}" ]; then
	_echot "------- fstab ext"
	uuidext=$( sudo blkid |grep ${_DEVICE_EXT} |sed 's|.* UUID="\([^"]\+\)" .*|\1|' )
	if [ -z "${uuidext}" ]; then
		_ask "Please give the UUID for ext"
		uuidext=${_ANSWER}
		_echO "uuidext=${uuidext}"
	fi

	sudo sh -c "echo '
	UUID=${uuidext}		/ext		ext4	errors=remount-ro		0 1' >> ${file}"

	_echot "------- mount /ext"
	_evalr mount UUID=${uuidext} /ext || _exite "Unable to mount UUID=${uuidext} in /ext"
	_evalr umount /ext
fi

_echot "------- ${file}"
echo
cat ${file}
echo
_echoA "Check above file: /etc/fstab"
_askno "Confirm to continue"
[ "${_ANSWER}" = n ] && exit 1


########################  REPO

_echot "------- repo - ${_GIT_BR}"
pth=${pth_sys}/usr/local/install
[ -d ${pth} ] && _keepmvts ${pth}
url=https://github.com/aguytech/desktop-${_VER_NAME}
_evalr git clone -b ${_GIT_BR} ${url} ${pth}
_evalr chown -R ${uid}:${gid} ${pth}

_echot "------- bs - ${_GIT_BR}"
pth=${pth_sys}/usr/local/bs
[ -d ${pth} ] && _keepmvts ${pth}
url=https://github.com/aguytech/bs-desktop
_evalr git clone -b ${_GIT_BR} ${url} ${pth}
_evalr chown -R ${uid}:${gid} ${pth}

########################  END

_partadd "${_PART}" "${S_FILE_INSTALL_DONE}"

########################  EXPORT

# installation system
if [ "${pth_sys}" != / ]; then
	_echot "------- copy config"
	pth="${pth_home}/${_USERNAME}/${_PATH_CONF}"
	_keepmvts ${pth}
	_evalr cp -r ${_PATH_CONF}/* ${pth}/
	_evalr chown ${uid}:${gid} -R ${pth}
	_evalr chmod 770 ${pth}

	_echot "------- copy log"
	pth="${pth_sys}${_PATH_LOG}"
	_keepmvts ${pth}
	_evalr cp -a ${_PATH_LOG} ${pth}/
	_evalr chown 0:${gid} -R ${pth}
	_evalr chmod 774 ${pth}
fi

###########  UMOUNT _DEVICE_SYS pth_sys

_echot "------- umount ${pth_sys}"
_evalr umount ${pth_sys}

###########  UMOUNT _DEVICE_HOME pth_home

_echot "------- umount ${pth_home}"
_evalr umount ${pth_home}

_echot "------- reboot ${_DEVICE_SYS}"
_echoA "You have to restart this installation script after the reboot"
_echoa "The computer now will reboot"
_askno "Validate to continue"
reboot
exit
