#!/bin/bash

########################  REPOSITORIES

_echot "------- apt repository"
file=/etc/apt/sources.list
_keepcpts ${file}

sudo add-apt-repository -yn ppa:mozillateam/ppa # mozilla
sudo add-apt-repository -yn ppa:tomtomtom/gmusicbrowser # gmusicbrowser
sudo apt-add-repository -yn ppa:vincent-vandevyvre/vvv # qarte
sudo apt-add-repository -yn ppa:kdenlive/kdenlive-stable
sudo apt-add-repository -yn ppa:inkscape.dev/stable # inkscape
sudo apt-add-repository -yn ppa:ubuntuhandbook1/darktable # darktable
#sudo apt-add-repository -yn ppa:yannubuntu/boot-repair # boot-repair
#sudo apt-add-repository -yn ppa:nilarimogard/webupd8 # youtube-dl, pulseaudio-equalizer & more
#sudo apt-add-repository -yn ppa:webupd8team/y-ppa-manager # y-ppa-manager
#sudo apt-add-repository -yn ppa:mc3man/mpv-tests # mpv
#sudo apt-add-repository -yn ppa:otto-kesselgulasch/gimp # gimp gmic

_echot "------- apt update"
_evalr apt update