#!/bin/bash

########################  MAIN

_echot "------- openssh-client"
packages="openssh-client"
_install_pcks ${packages}

_echot "------- client conf"
file=/etc/ssh/ssh_config
_keepcpts ${file}
sudo sed -i "s/^#\(\s*GSSAPIAuthentication\).*/ \1 no/" ${file}
sudo sed -i "/Host\s\+\*/ s|#\s\+||" ${file}
! sudo grep -q ServerAliveInterval ${file} && sudo sh -c "echo '    ServerAliveInterval 240' >> ${file}"

_echot "------- server conf"
file=/etc/ssh/sshd_config
if [ -f "${file}" ]; then
	_keepcpts ${file}
	! grep -q "UseDNS" ${file} && echo "UseDNS no" | sudo tee -a ${file}
	_service restart sshd
fi
