#!/bin/bash

########################  PRE OUTSIDE

_echot "------- libdvd"
_echo "Launch this following command in an other terminal:"
_echoA "sudo apt install -y libdvdnav4 libdvd-pkg libdvdread8t64"
_askno "After it, Validate to continue"

_echot "------- libdvd conf"
_echo "Launch this following command in an other terminal:"
_echoA "sudo dpkg-reconfigure libdvd-pkg"
_askno "After it, Validate to continue"
