#!/bin/bash

########################  INSTALL

packages="gedit-plugins gedit-source-code-browser-plugin stopwatch"
# gedit-developer-plugins
_install_pcks ${packages}

########################  CONF

_echot "------- gedit plugins path"
pth_plug=${HOME}/.local/share/gedit/plugins
[ -d "${pth_plug}" ] || mkdir -p "${pth_plug}"

pth=gedit-restore-tabs
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/raelgc/gedit-restore-tabs ${pth}
sudo cp ${pth}/org.gnome.gedit.plugins.restoretabs.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/

pth=gedit-duplicate-line
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/hardpixel/gedit-duplicate-line ${pth}
# use ALT-d instead of CTRL-d
sed -i.bak 's|\(Gdk.ModifierType.\).*:|\1MOD1_MASK:|' ${pth}/duplicate_line.py

pth=duplicate
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/hannenz/duplicate ${pth}
# use Shift-Ctrl-d, Shift-Alt-d or Alt-d
sed -i.bak "/\s'key': \[.*\],/ s|\[.*\]|['<Shift><Ctrl>d', '<Shift><Alt>d', '<Alt>d']|" ${pth}/duplicateline.py
tar czf ${pth}.tgz ${pth} && rm -fR ${pth}

pth=gedit-restore-minimap
_echot "------- gedit / ${pth}"
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/johnfactotum/gedit-restore-minimap.git ${pth}

pth=gedit-markdown_preview
_echot "------- gedit / ${pth}"
_install_pcks python3-markdown gir1.2-webkit2-4.1 libglib2.0-bin
cd ${pth_plug}
_keepmvts ${pth}
git clone https://github.com/maoschanz/gedit-plugin-markdown_preview ${pth}
cd ${pth_plug}/${pth} && _eval ./install.sh

_echot "------- gedit settings"
dconf write /org/gnome/gedit/preferences/editor/use-default-font true
dconf write /org/gnome/gedit/preferences/editor/tabs-size 4
dconf write /org/gnome/gedit/preferences/ui/side-panel-visible true
dconf write /org/gnome/gedit/preferences/editor/bracket-matching true
dconf write /org/gnome/gedit/preferences/editor/display-line-numbers true
dconf write /org/gnome/gedit/preferences/editor/highlight-current-line true
dconf write /org/gnome/gedit/plugins/active-plugins "['git', 'bookmarks', 'spell', 'sort', 'quickhighlight', 'modelines', 'filebrowser', 'docinfo', 'duplicate_line', 'restoretabs']"

########################  LAUNCHER

pth=~/.local/share/applications
[ -d "${pth}" ] || mkdir -p ${pth}

_echot "------- gedit"
name=org.gnome.gedit
file=/usr/share/applications/${name}.desktop
if [ -f ${file} ]; then
	_eval cp --update=all ${file} ${pth}
	if ! grep -q '\[Desktop Action Separator\]' ${pth}/${name}.desktop; then
		menuadd="Meld;GHex;Separator;Terminal;SshcDev;Sshc;SshcLxd"
		grep -q '^Actions=' ${pth}/${name}.desktop \
			&& sed -i "s|^\(Actions=.*\)$|\1${menuadd}|" ${pth}/${name}.desktop \
			|| echo "Actions=${menuadd}" >> ${pth}/${name}.desktop
		echo "
[Desktop Action Separator]
Name=−−−−−−−−−−
Exec=

[Desktop Action Meld]
Name=Meld
Exec=meld

[Desktop Action GHex]
Name=GHex
Exec=ghex

[Desktop Action SnapperGui]
Name=Snapper GUI
Exec=gksudo snapper-gui

[Desktop Action Terminal]
Name=Terminal
Exec=gnome-terminal

[Desktop Action SshcDev]
Name=sshc dev
Exec=gnome-terminal --tab --tab-with-profile node1

[Desktop Action Sshc]
Name=sshc
Exec=gnome-terminal -e ssh-server

[Desktop Action SshcLxd]
Name=sshcl
Exec=gnome-terminal -e ssh-lxd
" >> ${pth}/${name}.desktop
	fi
else
	_echoe "${name} are skipped"
	_echoe "${file} file not found"
fi

########################  AUTOSTART

pth=~/.config/autostart
! [ -d ${pth} ] && mkdir ${pth}

_echot "------- gedit add disabled"

file=${pth}/60-org.gnome.gedit.desktop
echo "[Desktop Entry]
Name=gedit
GenericName=Text Editor
Comment=Edit text files
Exec=gedit %U
Terminal=false
Type=Application
Icon=accessories-text-editor
Categories=GNOME;GTK;Utility;TextEditor;
StartupNotify=true
DBusActivatable=true
X-GNOME-Autostart-Delay=6
X-GNOME-Autostart-enabled=false
Hidden=true" > ${file}
chmod +x "${file}"
