#!/bin/bash

########################  REMOVE

_echot "------- firefox remove snap"
_evalr snap remove --purge firefox

_echot "------- firefox remove"
_evalr apt remove -y --purge firefox*

########################  FIREFOX

_echot "------- block snap"
echo 'Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1000' | sudo tee /etc/apt/preferences.d/mozillateam

_echot "------- firefox add ppa"
_evalr add-apt-repository -yn ppa:mozillateam/ppa

_echot "------- apt update"
_evalr apt update

_echot "------- firefox install"
_install_pcks firefox

_echot "------- firefox profile"
_echoA "Choose the right path to create a profile & close application"
_askno "Validate to continue"
firefox --ProfileManager

_echot "------- firefox launcher"
name=firefox
file=/usr/share/applications/${name}.desktop
pth=~/.local/share/applications
[ -f ${file} ] && _eval cp --update=all ${file} ${pth}
