#!/bin/bash

#############  DATA

anstmp=~/.themes/.origin
_askno "Give the path to install themes (${anstmp})"
pth_origin=${_ANSWER:-${anstmp}}

#############  MAIN

[ -d ${pth_origin} ] || _eval mkdir -p ${pth_origin}
cd ${pth_origin}

#############  ORCHIS

id=Orchis-theme
_echot "------- install ${id}"
if ! [ -d ${id} ]; then
	file=$(ls -1 | grep "^${id}_.*\.tgz" | head -n1)
	[ "${file}" ] && _eval tar xzf ${file}
fi
[ -d "${id}" ] || _eval git clone https://github.com/vinceliuice/${id} ${id}
_eval git -C ${id} pull
_eval ${id}/install.sh -d ~/.themes -c dark -s compact -l
_eval ${id}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px
_eval ${id}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px -t teal
_eval ${id}/install.sh -d ~/.themes -c dark -s compact -l --shell --round 8px -t orange
[ "${file}" ] && _eval rm ${file}
tar czf ${id}_$(date "+%Y%m%d").tgz ${id}

theme=Orchis-Orange-Dark-Compact

########################  DATA

_askyn "Apply themes '${theme}'' to desktop"
if [ "${_ANSWER}" = y ]; then
	gsettings set org.gnome.desktop.interface gtk-theme "${theme}"
	gsettings set org.gnome.desktop.wm.preferences theme "${theme}"
	gsettings set org.gnome.desktop.interface icon-theme "${theme}"
fi

_echoA "You can change the theme from 'gnome-tweaks'"
_askno "Validate to continue"

########################  BACKUP

for i in $(ls); do
	tar czf ${i}_$(date "+%Y%m%d").tgz $i
done
