#!/bin/bash

#########################  VARIABLES

export ZSH_CUSTOM=${HOME}/.oh-my-zsh/custom

#########################  ZSH

_echot "------- install"
packages="zsh"
_install_pcks ${packages}

_echot "------- zprofile"
file=/etc/zsh/zprofile
_keepcpts ${file}
sudo sh -c "echo '
# source /etc/profile 
emulate sh -c \"source /etc/profile\"' >> ${file}"

#########################  OH-MY-ZSH

_echot "------- .zshrc keep"
file=${HOME}/.zshrc
if [ -f ${file} ] && ! [ -f "${file}.before-ohmyovh" ]; then
	 mv ${file} ${file}.before-ohmyovh
fi

_echot "------- needed packages"
packages="git fonts-font-awesome"
_install_pcks ${packages}

_echot "------- oh-my-zsh"
_echo "Launch this following command in an other terminal:"
_echoA 'sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -qO -)"'
_echo 'After it, you can then close the terminal in which you launched the command'
_askno "Validate to continue"

pth=${ZSH_CUSTOM}/plugins/zsh-autosuggestions
if ! [ -d "${pth}" ]; then
	_echot "------- zsh-autosuggestions"
	_eval git clone https://github.com/zsh-users/zsh-autosuggestions ${pth}
fi

pth=${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting
if ! [ -d "${pth}" ]; then
	_echot "------- zsh-syntax-highlighting"
	_eval git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${pth}
fi

pth=${ZSH_CUSTOM}/themes/powerlevel10k
if ! [ -d "${pth}" ]; then
	_echot "------- powerlevel10k"
	_eval git clone https://github.com/romkatv/powerlevel10k.git ${pth}
fi

#########################  CONF

if ! [ -f "${file}.ohmyovh" ]; then
	_echot "-------- .zshrc"
	plugins='zsh-autosuggestions zsh-syntax-highlighting'
	sed -i.ohmyovh "s|^\(plugins=(.*\))|\1 ${plugins})|" ${file}
	theme='powerlevel10k/powerlevel10k'
	sed -i "/^ZSH_THEME=/ s|=.*$|=\"${theme}\"|" ${file}
	cat ${file} ${file}.before-ohmyovh > ${file}.tmp
	mv ${file}.tmp ${file}
fi

_echot "------- powerlevel10k"
_echo "Now you have to finish by configuring powerlevel10k :o)"
_echo "Launch this following command in an other terminal:"
_echoA 'zsh'
_askno "Validate to continue"
